// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/PartsOf.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class PartsOf {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=7;
      Object c=$fix(PartsOf.createCoder());
      $line=8;
      Object d=$fix(PartsOf.createCoder());
      $line=9;
      Utilities.testCodeDecode($cast(gold.structures.automaton.ITransducer.class,c),$cast(gold.structures.automaton.ITransducer.class,d));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PartsOf.class,"main",$line);
    }
  }
  public static Object w=null;
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      Object estado=$fix($opUnionY($opIntvlY('0','3'),GCollections.asSet("")));
      $line=17;
      w=$fix("");
      $line=19;
      Object Q=$fix($opUnionY($opCartsY(new Object[]{estado,estado,estado,estado}),GCollections.asSet("Error")));
      $line=20;
      Object \u03A3=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('0','3')));
      $line=21;
      Object Out=$fix($opUnionY($opUnionY($opIntvlY('0','3'),$opIntvlY('a','z')),GCollections.asSet('*')));
      $line=22;
      Object q_0=$fix(GCollections.asList("","","",""));
      $line=23;
      Object F=$fix(Q);
      $line=24;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(PartsOf.class,"\u03B4"),new GMethod(PartsOf.class,"g"),new GMethod(PartsOf.class,"h")});
      if (true) break $try;
      $line=25;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PartsOf.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=31;
      $result="Error";
      if (true) break $try;
      $line=33;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PartsOf.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v1, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object d0=$v2.next();
      Object d1=$v2.next();
      Object d2=$v2.next();
      Object d3=$v2.next();
      $line=37;
      if (($opEqualY(d0,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
        $line=37;
        $result=GCollections.asList(s,d1,d2,d3);
        if (true) break $try;
      }
      else {
        $line=39;
        if (($opEqualY(d1,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
          $line=39;
          $result=GCollections.asList(d0,s,d2,d3);
          if (true) break $try;
        }
        else {
          $line=41;
          if (($opEqualY(d2,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
            $line=41;
            $result=GCollections.asList(d0,d1,s,d3);
            if (true) break $try;
          }
          else {
            $line=43;
            if (($opEqualY(d3,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
              $line=43;
              $result=GCollections.asList(d0,d1,d2,s);
              if (true) break $try;
            }
            else {
              $line=45;
              if ((!$opEqualY(d3,"")&&$opMembrY(s,$opIntvlY('a','z')))) {
                $line=47;
                Object len=$fix($invokeMethod("length",w,new Object[]{}));
                $line=49;
                if ($opEqualY(len,0)) {
                  $line=51;
                  w=$fix(Character.toString($cast(char.class,s)));
                  $line=53;
                  $result=w;
                  if (true) break $try;
                }
                else {
                  $line=55;
                  if ($opEqualY(len,1)) {
                    $line=57;
                    w=$fix($opAdditY(w,Character.toString($cast(char.class,s))));
                    $line=59;
                    $result=w;
                    if (true) break $try;
                  }
                  else {
                    $line=61;
                    if ($opEqualY(len,2)) {
                      $line=63;
                      w=$fix($opAdditY(w,Character.toString($cast(char.class,s))));
                      $line=64;
                      $result=w;
                      if (true) break $try;
                    }
                    else {
                      $line=65;
                      if ($opEqualY(len,4)) {
                        $line=67;
                        w=$fix("");
                        $line=68;
                        $result=w;
                        if (true) break $try;
                      }
                      else {
                        $line=70;
                        $result="Error";
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
              else {
                $line=74;
                $result="Error";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=78;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8d0,d1,d2,d3\u27E9:java.lang.Iterable,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PartsOf.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=81;
      $result="";
      if (true) break $try;
      $line=82;
      $rethrow(new RuntimeException("The function \"h(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PartsOf.class,"h",$line);
    }
    return $result;
  }
  public static Object g(java.lang.Iterable $v3, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object d0=$v4.next();
      Object d1=$v4.next();
      Object d2=$v4.next();
      Object d3=$v4.next();
      $line=87;
      Object len=$fix($invokeMethod("length",w,new Object[]{}));
      $line=89;
      if (((((($opEqualY(len,3)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))&&$opMembrY(s,$opIntvlY('a','z')))) {
        $line=91;
        Object w_x=$fix($opAdditY(w,s));
        $line=92;
        $result=$opAdditY($opAdditY($opAdditY($opAdditY($invokeMethod("charAt",w_x,new Object[]{d0}),$invokeMethod("charAt",w_x,new Object[]{d1})),$invokeMethod("charAt",w_x,new Object[]{d2})),$invokeMethod("charAt",w_x,new Object[]{d3})),"");
        if (true) break $try;
      }
      else {
        $line=94;
        if ((((($opEqualY(len,4)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
          $line=96;
          Object w_x=$fix(w);
          $line=97;
          $result=$opAdditY($opAdditY($opAdditY($opAdditY($invokeMethod("charAt",w_x,new Object[]{d0}),$invokeMethod("charAt",w_x,new Object[]{d1})),$invokeMethod("charAt",w_x,new Object[]{d2})),$invokeMethod("charAt",w_x,new Object[]{d3})),"");
          if (true) break $try;
        }
        else {
          $line=99;
          if ((((($opEqualY(len,0)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
            $line=101;
            Object d=$fix($invokeConstructor(GArrayList.class,new Object[]{}));
            $line=102;
            ((gold.structures.list.GArrayList)d).add(d0);
            $line=103;
            ((gold.structures.list.GArrayList)d).add(d1);
            $line=104;
            ((gold.structures.list.GArrayList)d).add(d2);
            $line=105;
            ((gold.structures.list.GArrayList)d).add(d3);
            $line=107;
            Object inverso=$fix($invokeConstructor(GArrayList.class,new Object[]{}));
            $line=108;
            ((gold.structures.list.GArrayList)inverso).add(0);
            $line=109;
            ((gold.structures.list.GArrayList)inverso).add(0);
            $line=110;
            ((gold.structures.list.GArrayList)inverso).add(0);
            $line=111;
            ((gold.structures.list.GArrayList)inverso).add(0);
            $line=113;
            $setArrayValue(inverso,$fix(0),new Object[]{$getArrayValue(d,new Object[]{0})});
            $line=114;
            $setArrayValue(inverso,$fix(1),new Object[]{$getArrayValue(d,new Object[]{1})});
            $line=115;
            $setArrayValue(inverso,$fix(2),new Object[]{$getArrayValue(d,new Object[]{2})});
            $line=116;
            $setArrayValue(inverso,$fix(3),new Object[]{$getArrayValue(d,new Object[]{3})});
            $line=118;
            $result=inverso;
            if (true) break $try;
          }
          else {
            $line=120;
            if (((((($opEqualY($opModulY(len,4),0)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))&&$opEqualY(s,"$"))) {
              $line=121;
              $result="";
              if (true) break $try;
            }
            else {
              $line=123;
              if ((((($opEqualY(len,1)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
                $line=124;
                $result=$opAdditY(w,"***");
                if (true) break $try;
              }
              else {
                $line=126;
                if ((((($opEqualY(len,2)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
                  $line=127;
                  $result=$opAdditY(w,"**");
                  if (true) break $try;
                }
                else {
                  $line=129;
                  if ((((($opEqualY(len,3)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
                    $line=130;
                    $result=$opAdditY(w,"*");
                    if (true) break $try;
                  }
                  else {
                    $line=133;
                    $result="";
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      $line=136;
      $rethrow(new RuntimeException("The function \"g(\u27E8d0,d1,d2,d3\u27E9:java.lang.Iterable,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,PartsOf.class,"g",$line);
    }
    return $result;
  }
}
