// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/During_21_10_23.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class During_21_10_23 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=4;
      Object c=$fix(During_21_10_23.createCoder());
      $line=5;
      Object d=$fix(During_21_10_23.createCoder());
      $line=6;
      Utilities.testCodeDecode($cast(gold.structures.automaton.ITransducer.class,c),$cast(gold.structures.automaton.ITransducer.class,d));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,During_21_10_23.class,"main",$line);
    }
  }
  public static Object w=null;
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=13;
      Object estado=$fix($opUnionY($opIntvlY('0','3'),GCollections.asSet("")));
      $line=14;
      w=$fix("");
      $line=16;
      Object Q=$fix($opUnionY($opUnionY($opCartsY(new Object[]{estado,estado,estado,estado}),GCollections.asSet("Error")),$opIntvlY('a','z')));
      $line=17;
      Object \u03A3=$fix($opUnionY($opIntvlY('a','z'),$opIntvlY('0','3')));
      $line=18;
      Object Out=$fix($opUnionY(\u03A3,GCollections.asSet('*')));
      $line=19;
      Object q_0=$fix(GCollections.asList("","","",""));
      $line=20;
      Object F=$fix(Q);
      $line=21;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(During_21_10_23.class,"\u03B4"),new GMethod(During_21_10_23.class,"g"),new GMethod(During_21_10_23.class,"h")});
      if (true) break $try;
      $line=22;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,During_21_10_23.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=28;
      $result="Error";
      if (true) break $try;
      $line=30;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,During_21_10_23.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B4(java.lang.Iterable $v1, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object d0=$v2.next();
      Object d1=$v2.next();
      Object d2=$v2.next();
      Object d3=$v2.next();
      $line=34;
      if (($opEqualY(d0,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
        $line=34;
        $result=GCollections.asList(s,d1,d2,d3);
        if (true) break $try;
      }
      else {
        $line=36;
        if (($opEqualY(d1,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
          $line=36;
          $result=GCollections.asList(d0,s,d2,d3);
          if (true) break $try;
        }
        else {
          $line=38;
          if (($opEqualY(d2,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
            $line=38;
            $result=GCollections.asList(d0,d1,s,d3);
            if (true) break $try;
          }
          else {
            $line=40;
            if (($opEqualY(d3,"")&&$opMembrY(s,$opIntvlY('0','3')))) {
              $line=40;
              $result=GCollections.asList(d0,d1,d2,s);
              if (true) break $try;
            }
            else {
              $line=42;
              if ((!$opEqualY(d3,"")&&$opMembrY(s,$opIntvlY('a','z')))) {
                $line=44;
                Object len=$fix($invokeMethod("length",w,new Object[]{}));
                $line=46;
                if ($opEqualY(len,0)) {
                  $line=48;
                  w=$fix(Character.toString($cast(char.class,s)));
                  $line=50;
                  $result=GCollections.asList(d0,d1,d2,d3);
                  if (true) break $try;
                }
                else {
                  $line=52;
                  if ($opEqualY(len,1)) {
                    $line=54;
                    w=$fix($opAdditY(w,Character.toString($cast(char.class,s))));
                    $line=56;
                    $result=GCollections.asList(d0,d1,d2,d3);
                    if (true) break $try;
                  }
                  else {
                    $line=58;
                    if ($opEqualY(len,2)) {
                      $line=60;
                      w=$fix($opAdditY(w,Character.toString($cast(char.class,s))));
                      $line=61;
                      $result=GCollections.asList(d0,d1,d2,d3);
                      if (true) break $try;
                    }
                    else {
                      $line=62;
                      if ($opEqualY(len,4)) {
                        $line=64;
                        w=$fix("");
                        $line=65;
                        $result=GCollections.asList(d0,d1,d2,d3);
                        if (true) break $try;
                      }
                      else {
                        $line=67;
                        $result="Error";
                        if (true) break $try;
                      }
                    }
                  }
                }
              }
              else {
                $line=71;
                $result="Error";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=75;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8d0,d1,d2,d3\u27E9:java.lang.Iterable,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,During_21_10_23.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=78;
      $result="";
      if (true) break $try;
      $line=79;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,During_21_10_23.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=82;
      $result="";
      if (true) break $try;
      $line=83;
      $rethrow(new RuntimeException("The function \"h(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,During_21_10_23.class,"h",$line);
    }
    return $result;
  }
  public static Object h(java.lang.Iterable $v3, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object d0=$v4.next();
      Object d1=$v4.next();
      Object d2=$v4.next();
      Object d3=$v4.next();
      $line=88;
      Object len=$fix($invokeMethod("length",w,new Object[]{}));
      $line=90;
      if (((((($opEqualY(len,3)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))&&$opMembrY(s,$opIntvlY('a','z')))) {
        $line=91;
        Object w_x=$fix($opAdditY(w,s));
        $line=93;
        $result=$opAdditY($opAdditY($opAdditY($opAdditY("",$invokeMethod(String.class,"valueOf",true,null,new Object[]{$invokeMethod("charAt",w_x,new Object[]{Integer.parseInt($cast(java.lang.String.class,$invokeMethod(String.class,"valueOf",true,null,new Object[]{d0})))})})),$invokeMethod(String.class,"valueOf",true,null,new Object[]{$invokeMethod("charAt",w_x,new Object[]{Integer.parseInt($cast(java.lang.String.class,$invokeMethod(String.class,"valueOf",true,null,new Object[]{d1})))})})),$invokeMethod(String.class,"valueOf",true,null,new Object[]{$invokeMethod("charAt",w_x,new Object[]{Integer.parseInt($cast(java.lang.String.class,$invokeMethod(String.class,"valueOf",true,null,new Object[]{d2})))})})),$invokeMethod(String.class,"valueOf",true,null,new Object[]{$invokeMethod("charAt",w_x,new Object[]{Integer.parseInt($cast(java.lang.String.class,$invokeMethod(String.class,"valueOf",true,null,new Object[]{d3})))})}));
        if (true) break $try;
      }
      else {
        $line=95;
        if (((((($opEqualY(len,0)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))&&$opMembrY(s,$opIntvlY('0','3')))) {
          $line=97;
          Object d=$fix($invokeConstructor(GArrayList.class,new Object[]{}));
          $line=98;
          ((gold.structures.list.GArrayList)d).add(d0);
          $line=99;
          ((gold.structures.list.GArrayList)d).add(d1);
          $line=100;
          ((gold.structures.list.GArrayList)d).add(d2);
          $line=101;
          ((gold.structures.list.GArrayList)d).add(d3);
          $line=103;
          Object inverso=$fix($invokeConstructor(GArrayList.class,new Object[]{}));
          $line=104;
          ((gold.structures.list.GArrayList)inverso).add(0);
          $line=105;
          ((gold.structures.list.GArrayList)inverso).add(0);
          $line=106;
          ((gold.structures.list.GArrayList)inverso).add(0);
          $line=107;
          ((gold.structures.list.GArrayList)inverso).add(0);
          $line=109;
          $setArrayValue(inverso,$fix(0),new Object[]{$getArrayValue(d,new Object[]{0})});
          $line=110;
          $setArrayValue(inverso,$fix(1),new Object[]{$getArrayValue(d,new Object[]{1})});
          $line=111;
          $setArrayValue(inverso,$fix(2),new Object[]{$getArrayValue(d,new Object[]{2})});
          $line=112;
          $setArrayValue(inverso,$fix(3),new Object[]{$getArrayValue(d,new Object[]{3})});
          $line=114;
          $result=inverso;
          if (true) break $try;
        }
        else {
          $line=116;
          if (((((($opEqualY($opModulY(len,4),0)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))&&$opEqualY(s,"$"))) {
            $line=117;
            $result="";
            if (true) break $try;
          }
          else {
            $line=119;
            if ((((($opEqualY(len,1)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
              $line=120;
              $result=$opAdditY(w,"***");
              if (true) break $try;
            }
            else {
              $line=122;
              if ((((($opEqualY(len,2)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
                $line=123;
                $result=$opAdditY(w,"**");
                if (true) break $try;
              }
              else {
                $line=125;
                if ((((($opEqualY(len,3)&&!$opEqualY(d0,""))&&!$opEqualY(d1,""))&&!$opEqualY(d2,""))&&!$opEqualY(d3,""))) {
                  $line=126;
                  $result=$opAdditY(w,"*");
                  if (true) break $try;
                }
                else {
                  $line=129;
                  $result="";
                  if (true) break $try;
                }
              }
            }
          }
        }
      }
      $line=132;
      $rethrow(new RuntimeException("The function \"h(\u27E8d0,d1,d2,d3\u27E9:java.lang.Iterable,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,During_21_10_23.class,"h",$line);
    }
    return $result;
  }
}
