// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/LexerParserRobot202310.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class LexerParserRobot202310 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object chars(Object string) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v1=$newSet();
      int $v3=$int(0);
      int $v4=$int($invokeMethod("length",string,new Object[]{}))-1;
      $v2:for (int i=$v3; i<=$v4; i++) {
        $v1.add($invokeMethod("charAt",string,new Object[]{i}));
      }
      $result=$v1;
      if (true) break $try;
      $line=7;
      $rethrow(new RuntimeException("The function \"chars(string:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"chars",$line);
    }
    return $result;
  }
  public static Object charsStrings(Object strings) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v5=$newSet(GCollections.emptySet());
      $v6:for (Object s:GCollections.unmodifiableCollection(strings)) {
        $v5.union(GCollections.unmodifiableSet(((java.lang.Iterable)($invokeMethod(LexerParserRobot202310.class,"chars",true,null,new Object[]{s})))));
      }
      $result=$v5;
      if (true) break $try;
      $line=8;
      $rethrow(new RuntimeException("The function \"charsStrings(strings:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"charsStrings",$line);
    }
    return $result;
  }
  public static Object elements(Object array) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v7=$newSet();
      int $v9=$int(0);
      int $v10=$int($opAbsolY(array))-1;
      $v8:for (int i=$v9; i<=$v10; i++) {
        $v7.add($getArrayValue(array,new Object[]{i}));
      }
      $result=$v7;
      if (true) break $try;
      $line=9;
      $rethrow(new RuntimeException("The function \"elements(array:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"elements",$line);
    }
    return $result;
  }
  public static Object get1(java.lang.Iterable $v11) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v12=GCollections.unmodifiableCollection($v11).iterator();
      Object r=$v12.next();
      Object i=$v12.next();
      $result=r;
      if (true) break $try;
      $line=10;
      $rethrow(new RuntimeException("The function \"get1(\u27E8r,i\u27E9:java.lang.Iterable)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"get1",$line);
    }
    return $result;
  }
  public static Object get2(java.lang.Iterable $v13) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v14=GCollections.unmodifiableCollection($v13).iterator();
      Object r=$v14.next();
      Object i=$v14.next();
      $result=i;
      if (true) break $try;
      $line=11;
      $rethrow(new RuntimeException("The function \"get2(\u27E8r,i\u27E9:java.lang.Iterable)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"get2",$line);
    }
    return $result;
  }
  public static GDeterministicTransducer lexer=null;
  static {
    int $line=0;
    $line=14;
    $try:try {
      lexer=$defaultValue(GDeterministicTransducer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,null,$line);
    }
  }
  public static GPushdownAutomaton parser=null;
  static {
    int $line=0;
    $line=15;
    $try:try {
      parser=$defaultValue(GPushdownAutomaton.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,null,$line);
    }
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=18;
      Object currentString=$fix("");
      $line=20;
      lexer=$cast(GDeterministicTransducer.class,$fix($invokeMethod("createLexer",$invokeField(Lexer202310.class,"Lexer202310",true,null),new Object[]{})));
      $line=22;
      parser=$cast(GPushdownAutomaton.class,$fix($invokeMethod("createParser",$invokeField(ParserRobot202310.class,"ParserRobot202310",true,null),new Object[]{((gold.structures.automaton.GDeterministicTransducer)lexer).getOutputAlphabet()})));
      $line=30;
      $invokeMethod(LexerParserRobot202310.class,"testLexerParser",true,null,new Object[]{lexer,parser});
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"main",$line);
    }
  }
  public static Object testLexer(ITransducer M) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=35;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=36;
      String string=null;
      string=$defaultValue(String.class);
      $line=37;
      String input=null;
      input=$defaultValue(String.class);
      $line=40;
      Object inputA=$fix($invokeMethod(LexerParserRobot202310.class,"elements",true,null,new Object[]{((gold.structures.automaton.ITransducer)M).getInputAlphabet()}));
      $line=41;
      input=$cast(String.class,$fix(""));
      $line=42;
      System.out.println($message(new Object[]{"----------------------------"}));
      $line=43;
      System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
      $line=44;
      System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
      $line=45;
      string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      $line=46;
      while (true) {
        if (!(!$opEqualY(string,"EXIT"))) break;
        $line=47;
        string=$cast(String.class,$fix($opAdditY(string," \n ")));
        $line=48;
        input=$cast(String.class,$fix(""));
        $line=49;
        while (true) {
          if (!(!$opEqualY(((java.lang.String)string).charAt($int(0)),'$'))) break;
          $line=50;
          input=$cast(String.class,$fix($opAdditY(input,string)));
          $line=51;
          string=$cast(String.class,$fix($opAdditY(((java.util.Scanner)sc).nextLine()," \n  ")));
        }
        $line=53;
        if ($opSbsetY($invokeMethod(LexerParserRobot202310.class,"chars",true,null,new Object[]{input}),inputA)) {
          $line=54;
          Object currentString=$fix("");
          $line=55;
          Object images=$fix($invokeConstructor(GArrayList.class,new Object[]{}));
          $line=57;
          Object result=$fix($invokeMethod("runLexer",$invokeField(Lexer202310.class,"Lexer202310",true,null),new Object[]{M,input}));
          $line=60;
          Object ok=$fix($invokeMethod(LexerParserRobot202310.class,"get1",true,null,new Object[]{result}));
          $line=61;
          images=$fix($invokeMethod(LexerParserRobot202310.class,"get2",true,null,new Object[]{result}));
          $line=62;
          Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
          $line=64;
          System.out.println($message(new Object[]{$opAdditY($opAdditY("The input was ",(($bool(ok))?(""):("not ")))," accepted by the lexer.")}));
          $line=65;
          if ($bool(ok)) {
            $line=66;
            System.out.println($message(new Object[]{$opAdditY("Token Stream:  ",tokenStream)}));
            $line=67;
            System.out.println($message(new Object[]{$opAdditY("Strings: ",images)}));
          }
          else {
            $line=68;
            System.out.println($message(new Object[]{$opAdditY("Partial token Stream ",tokenStream)}));
          }
        }
        else {
          $line=70;
          System.out.println($message(new Object[]{$opAdditY("Input contains invalid characters: ",$opDiffeY($invokeMethod(LexerParserRobot202310.class,"chars",true,null,new Object[]{input}),inputA))}));
        }
        $line=72;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=74;
        System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
        $line=75;
        System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
        $line=76;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      }
      $line=79;
      System.out.println($message(new Object[]{"Good bye"}));
      $line=80;
      System.out.println($message(new Object[]{""}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"testLexer",$line);
    }
    return $result;
  }
  public static Object testLexerParser(ITransducer M, IPushdownAutomaton P) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=91;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=92;
      String string=null;
      string=$defaultValue(String.class);
      $line=93;
      String input=null;
      input=$defaultValue(String.class);
      $line=96;
      Object inputA=$fix($invokeMethod(LexerParserRobot202310.class,"elements",true,null,new Object[]{((gold.structures.automaton.ITransducer)M).getInputAlphabet()}));
      $line=97;
      Object inputP=$fix($invokeMethod(LexerParserRobot202310.class,"elements",true,null,new Object[]{((gold.structures.automaton.IPushdownAutomaton)P).getInputAlphabet()}));
      $line=100;
      input=$cast(String.class,$fix(""));
      $line=103;
      System.out.println($message(new Object[]{"----------------------------"}));
      $line=104;
      System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
      $line=105;
      System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
      $line=106;
      string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      $line=111;
      while (true) {
        if (!(!$opEqualY(string,"EXIT"))) break;
        $line=113;
        string=$cast(String.class,$fix($opAdditY(string,"  \n ")));
        $line=114;
        input=$cast(String.class,$fix(""));
        $line=115;
        while (true) {
          if (!(!$opEqualY(((java.lang.String)string).charAt($int(0)),'$'))) break;
          $line=116;
          input=$cast(String.class,$fix($opAdditY(input,string)));
          $line=117;
          string=$cast(String.class,$fix($opAdditY(((java.util.Scanner)sc).nextLine()," \n ")));
        }
        $line=120;
        Object option=$fix("");
        $line=121;
        while (true) {
          if (!(!$opMembrY(option,GCollections.asSet("1","2","3")))) break;
          $line=122;
          System.out.println($message(new Object[]{"What do you want to do?"}));
          $line=123;
          System.out.println($message(new Object[]{"1. Lexer only?"}));
          $line=124;
          System.out.println($message(new Object[]{"2. Lexer and parser?"}));
          $line=125;
          System.out.println($message(new Object[]{"3. Parser?"}));
          $line=126;
          option=$fix(((java.util.Scanner)sc).nextLine());
        }
        $line=128;
        Object stringOut=$fix("");
        $line=129;
        if ($opMembrY(option,GCollections.asSet("1","2"))) {
          $line=130;
          if ($opSbsetY($invokeMethod(LexerParserRobot202310.class,"chars",true,null,new Object[]{input}),inputA)) {
            $line=131;
            Object currentString=$fix("");
            $line=132;
            Object images=$fix($invokeConstructor(GArrayList.class,new Object[]{}));
            $line=134;
            Object result=$fix($invokeMethod("runLexer",$invokeField(Lexer202310.class,"Lexer202310",true,null),new Object[]{M,input}));
            $line=137;
            Object ok=$fix($invokeMethod(LexerParserRobot202310.class,"get1",true,null,new Object[]{result}));
            $line=138;
            images=$fix($invokeMethod(LexerParserRobot202310.class,"get2",true,null,new Object[]{result}));
            $line=139;
            Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
            $line=144;
            System.out.println($message(new Object[]{$opAdditY($opAdditY("The input was ",(($bool(ok))?(""):("not ")))," accepted by the lexer.")}));
            $line=145;
            if ($bool(ok)) {
              $line=146;
              System.out.println($message(new Object[]{$opAdditY("Token Stream:  ",tokenStream)}));
              $line=147;
              System.out.println($message(new Object[]{$opAdditY("Strings: ",images)}));
              $line=148;
              if ($opEqualY(option,"2")) {
                $line=149;
                ok=$fix(((gold.structures.automaton.IPushdownAutomaton)P).acceptsString($cast(java.lang.String.class,tokenStream)));
                $line=150;
                System.out.println($message(new Object[]{$opAdditY("Parser result: ",(($bool(ok))?("accepted "):("rejected ")))}));
              }
            }
            else {
              $line=152;
              System.out.println($message(new Object[]{$opAdditY("Partial token Stream: ",tokenStream)}));
            }
          }
          else {
            $line=154;
            System.out.println($message(new Object[]{$opAdditY("Input contains invalid characters: ",$opDiffeY($invokeMethod(LexerParserRobot202310.class,"chars",true,null,new Object[]{input}),inputA))}));
          }
        }
        else {
          $line=157;
          if ($opSbsetY($invokeMethod(LexerParserRobot202310.class,"chars",true,null,new Object[]{input}),inputP)) {
            $line=158;
            Object ok=$fix(((gold.structures.automaton.IPushdownAutomaton)P).acceptsString($cast(java.lang.String.class,input)));
            $line=159;
            System.out.println($message(new Object[]{$opAdditY("Parser result: ",(($bool(ok))?("accepted "):("rejected ")))}));
          }
          else {
            $line=161;
            System.out.println($message(new Object[]{$opAdditY("Input contains invalid characters: ",$opDiffeY($invokeMethod(LexerParserRobot202310.class,"chars",true,null,new Object[]{input}),inputP))}));
          }
        }
        $line=164;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=166;
        System.out.println($message(new Object[]{"Enter one or more lines. End with a single line with $"}));
        $line=167;
        System.out.println($message(new Object[]{"If you want to stop testing, enter EXIT"}));
        $line=168;
        string=$cast(String.class,$fix(((java.util.Scanner)sc).nextLine()));
      }
      $line=171;
      System.out.println($message(new Object[]{"Good bye"}));
      $line=172;
      System.out.println($message(new Object[]{""}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParserRobot202310.class,"testLexerParser",$line);
    }
    return $result;
  }
}
