// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Pila.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Pila {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,Pila.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Pila.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=10;
      Object \u03A3=$fix(GCollections.asSet('1','+','-','=','0'));
      $line=12;
      Object Q=$fix(GCollections.asSet(0,1,2,4,5,7,8,9));
      $line=14;
      Object \u0393=$fix(GCollections.asSet('$','1'));
      $line=15;
      Object q_0=$fix(0);
      $line=16;
      Object F=$fix(GCollections.asSet(9));
      $line=17;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=19;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=20;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=21;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=22;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,"+")),new Object[]{"1"});
      $line=23;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,7,$cast(java.lang.String.class,"-")),new Object[]{"1"});
      $line=24;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,4,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=25;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,"=")),new Object[]{"1"});
      $line=26;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,7,$cast(java.lang.String.class,"-")),new Object[]{"1"});
      $line=27;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,5,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=28;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,9,$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=29;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=30;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,4,$cast(java.lang.String.class,"+")),new Object[]{"1"});
      $line=31;
      $invokeMethod("pushOn",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,8,$cast(java.lang.String.class,"1")),new Object[]{"$","1"});
      $line=32;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,5,$cast(java.lang.String.class,"=")),new Object[]{"1"});
      $line=33;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,8,$cast(java.lang.String.class,"1")),new Object[]{"1"});
      $line=34;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,5,$cast(java.lang.String.class,"=-")),new Object[]{"1"});
      $line=35;
      $result=M;
      if (true) break $try;
      $line=36;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Pila.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
